name: Test
on:
  push:
    branches: 
      - release/*
jobs:
  create_pr:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out actions
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run : npm install
      - name: Execute the action
        uses: ./gitactions/create-pr
