name: Test
on:
  push:
    branches: 
      - release/*
jobs:
  create_pr:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out actions
        uses: actions/checkout@develop
      - name: Execute the action
        uses: ./gitactions/create-pr
